### ISSUE TITLE
Formulaic / Poetry install top-level tests package

### ISSUE THREAD

**Issue by jseabold** [matthewwardrop/formulaic#73] opened 2022-04-15 15:19 UTC
Unclear to me what the issue is. I'm not familiar with poetry, but I have a top-level namespace package from formulaic that's called tests. Here is what I believe to be the relevant poetry issue https://github.com/python-poetry/poetry/issues/2353 with links to other packages that are running into this..

**Comment by matthewwardrop** [comment] 2022-04-25 04:42
Thanks for reporting this @jseabold ! Might not have noticed otherwise. Will check into it ahead of the next release.

**Comment by matthewwardrop** [comment] 2022-04-25 04:45
Hmmm... I took a quick look, and it looks like none of the distributed files are shipping with the `tests` module. How are you installing formulaic?

**Comment by jseabold** [comment] 2022-04-25 11:35
I installed lifelines via pip and formulaic was installed as a dependency.

**Comment by matthewwardrop** [comment] 2022-04-30 04:25
I've tried to reproduce this in a few different ways (including different versions of Python, with and without `wheel` installed), and I cannot.

```
python -m venv my_env
source my_env/bin/activate
pip install lifelines
```

This always installs formulaic, but I never see a toplevel `tests` module being installed.

Can you attempt to reproduce it? And if you can, let me know more details like: operating system and python versions, distribution of Python (system, conda, official), etc?

**Comment by matthewwardrop** [comment] 2022-06-20 17:28
I cannot reproduce this one, so I am going to close this out for now. If you see it happening again, let me know!

**Closed by matthewwardrop** 2022-06-20 17:28 UTC
Labels: bug, question
