### ISSUE TITLE
`_ordering="none"` is ignored when a dependent variable is included

### ISSUE THREAD

**Issue by eirki** [matthewwardrop/formulaic#191] opened 2024-09-05 07:43 UTC
Thanks for the very useful library!

I'm having some issues with retaining the order of the terms as they are in the formula. Using the example from the README, but with a `c  ~` added, yield the following result:

```python
In [2]: {
   ...:     "degree": Formula("c ~ z + z:a + z:b:a + g").rhs,
   ...:     "none": Formula("c ~ z + z:a + z:b:a + g", _ordering="none").rhs,
   ...:     "sort": Formula("c ~ z + z:a + z:b:a + g", _ordering="sort").rhs,
   ...: }
Out[2]:
{'degree': 1 + z + g + z:a + z:b:a,
 'none': 1 + z + g + z:a + z:b:a,
 'sort': 1 + g + z + a:z + a:b:z}
```

Notice the `'none'` example is identical to the `'degree'` (default) option. Is there a reason for this?

**Comment by matthewwardrop** [comment] 2024-10-17 16:54
Hmmm... that seems like a regression, since the behaviour in the docs indicates otherwise. I'll take a look at this shortly!

**Comment by matthewwardrop** [comment] 2024-10-20 04:38
@eirki I looked into this tonight, but wasn't able to reproduce the issue. Which version of formulaic are you using? Can you reproduce it in 1.0.2?

**Comment by matthewwardrop** [comment] 2024-11-16 06:41
This is now fixed in main, and will be released in the next version. Thanks for reporting!

**Closed** 2024-11-16 06:41 UTC
Labels: bug
