### ISSUE TITLE
17 tests fail:  ModuleNotFoundError: No module named 'interface_meta'

### ISSUE THREAD

**Issue by yurivict** [matthewwardrop/formulaic#127] opened 2022-12-28 22:11 UTC
```
========================================================================================== test session starts ==========================================================================================
platform freebsd13 -- Python 3.9.16, pytest-7.2.0, pluggy-1.0.0 -- /usr/local/bin/python3.9
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/usr/ports/math/py-formulaic/work-py39/formulaic-0.5.2/.hypothesis/examples')
Using --randomly-seed=2601068982
rootdir: /usr/ports/math/py-formulaic/work-py39/formulaic-0.5.2
plugins: forked-1.4.0, hypothesis-6.56.2, cov-2.9.0, randomly-3.12.0, timeout-2.1.0, freezegun-0.4.2, rerunfailures-10.1, flaky-3.7.0, xdist-2.5.0, env-0.6.2, mock-1.10.4, anyio-3.6.1, subtests-0.8.0, asyncio-0.20.3, trio-0.8.0, flake8-1.1.1
asyncio: mode=strict
collected 200 items / 17 errors                                                                                                                                                                         

================================================================================================ ERRORS =================================================================================================
________________________________________________________________________________ ERROR collecting tests/test_formula.py _________________________________________________________________________________
ImportError while importing test module '/usr/ports/math/py-formulaic/work-py39/formulaic-0.5.2/tests/test_formula.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_formula.py:8: in <module>
    from formulaic import Formula
formulaic/__init__.py:2: in <module>
    from .materializers import FactorValues
formulaic/materializers/__init__.py:1: in <module>
    from .arrow import ArrowMaterializer
formulaic/materializers/arrow.py:1: in <module>
    from interface_meta import override
E   ModuleNotFoundError: No module named 'interface_meta'
______________________________________________________________________________ ERROR collecting tests/test_model_matrix.py ______________________________________________________________________________
ImportError while importing test module '/usr/ports/math/py-formulaic/work-py39/formulaic-0.5.2/tests/test_model_matrix.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_model_matrix.py:7: in <module>
    from formulaic import (
formulaic/__init__.py:2: in <module>
    from .materializers import FactorValues
formulaic/materializers/__init__.py:1: in <module>
    from .arrow import ArrowMaterializer
formulaic/materializers/arrow.py:1: in <module>
    from interface_meta import override
E   ModuleNotFoundError: No module named 'interface_meta'
_______________________________________________________________________________ ERROR collecting tests/test_model_spec.py _______________________________________________________________________________
ImportError while importing test module '/usr/ports/math/py-formulaic/work-py39/formulaic-0.5.2/tests/test_model_spec.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_model_spec.py:10: in <module>
    from formulaic import Formula, ModelSpec, ModelSpecs, ModelMatrix, ModelMatrices
formulaic/__init__.py:2: in <module>
    from .materializers import FactorValues
formulaic/materializers/__init__.py:1: in <module>
    from .arrow import ArrowMaterializer
formulaic/materializers/arrow.py:1: in <module>
    from interface_meta import override
E   ModuleNotFoundError: No module named 'interface_meta'
_________________________________________________________________________________ ERROR collecting tests/test_sugar.py __________________________________________________________________________________
ImportError while importing test module '/usr/ports/math/py-formulaic/work-py39/formulaic-0.5.2/tests/test_sugar.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_sugar.py:5: in <module>
    from formulaic import model_matrix
formulaic/__init__.py:2: in <module>
    from .materializers import FactorValues
formulaic/materializers/__init__.py:1: in <module>
    from .arrow import ArrowMaterializer
formulaic/materializers/arrow.py:1: in <module>
    from interface_meta import override
E   ModuleNotFoundError: No module named 'interface_meta'
__________________________________________________________________________ ERROR collecting tests/materializers/test_arrow.py ___________________________________________________________________________
ImportError while importing test module '/usr/ports/math/py-formulaic/work-py39/formulaic-0.5.2/tests/materializers/test_arrow.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/materializers/test_arrow.py:6: in <module>
    from formulaic.materializers import ArrowMaterializer
formulaic/__init__.py:2: in <module>
    from .materializers import FactorValues
formulaic/materializers/__init__.py:1: in <module>
    from .arrow import ArrowMaterializer
formulaic/materializers/arrow.py:1: in <module>
    from interface_meta import override
E   ModuleNotFoundError: No module named 'interface_meta'
___________________________________________________________________________ ERROR collecting tests/materializers/test_base.py ___________________________________________________________________________
ImportError while importing test module '/usr/ports/math/py-formulaic/work-py39/formulaic-0.5.2/tests/materializers/test_base.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/materializers/test_base.py:5: in <module>
    from formulaic.materializers.types import (
formulaic/__init__.py:2: in <module>
    from .materializers import FactorValues
formulaic/materializers/__init__.py:1: in <module>
    from .arrow import ArrowMaterializer
formulaic/materializers/arrow.py:1: in <module>
    from interface_meta import override
E   ModuleNotFoundError: No module named 'interface_meta'
__________________________________________________________________________ ERROR collecting tests/materializers/test_pandas.py __________________________________________________________________________
ImportError while importing test module '/usr/ports/math/py-formulaic/work-py39/formulaic-0.5.2/tests/materializers/test_pandas.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/materializers/test_pandas.py:10: in <module>
    from formulaic import ModelMatrices
formulaic/__init__.py:2: in <module>
    from .materializers import FactorValues
formulaic/materializers/__init__.py:1: in <module>
    from .arrow import ArrowMaterializer
formulaic/materializers/arrow.py:1: in <module>
    from interface_meta import override
E   ModuleNotFoundError: No module named 'interface_meta'
__________________________________________________________________ ERROR collecting tests/materializers/types/test_evaluated_factor.py __________________________________________________________________
ImportError while importing test module '/usr/ports/math/py-formulaic/work-py39/formulaic-0.5.2/tests/materializers/types/test_evaluated_factor.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/materializers/types/test_evaluated_factor.py:4: in <module>
    from formulaic.materializers.types import EvaluatedFactor, FactorValues
formulaic/__init__.py:2: in <module>
    from .materializers import FactorValues
formulaic/materializers/__init__.py:1: in <module>
    from .arrow import ArrowMaterializer
formulaic/materializers/arrow.py:1: in <module>
    from interface_meta import override
E   ModuleNotFoundError: No module named 'interface_meta'
___________________________________________________________________ ERROR collecting tests/materializers/types/test_factor_values.py ____________________________________________________________________
ImportError while importing test module '/usr/ports/math/py-formulaic/work-py39/formulaic-0.5.2/tests/materializers/types/test_factor_values.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/materializers/types/test_factor_values.py:3: in <module>
    from formulaic.materializers.types import FactorValues
formulaic/__init__.py:2: in <module>
    from .materializers import FactorValues
formulaic/materializers/__init__.py:1: in <module>
    from .arrow import ArrowMaterializer
formulaic/materializers/arrow.py:1: in <module>
    from interface_meta import override
E   ModuleNotFoundError: No module named 'interface_meta'
___________________________________________________________________ ERROR collecting tests/materializers/types/test_scoped_factor.py ____________________________________________________________________
ImportError while importing test module '/usr/ports/math/py-formulaic/work-py39/formulaic-0.5.2/tests/materializers/types/test_scoped_factor.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/materializers/types/test_scoped_factor.py:3: in <module>
    from formulaic.materializers.types import ScopedFactor
formulaic/__init__.py:2: in <module>
    from .materializers import FactorValues
formulaic/materializers/__init__.py:1: in <module>
    from .arrow import ArrowMaterializer
formulaic/materializers/arrow.py:1: in <module>
    from interface_meta import override
E   ModuleNotFoundError: No module named 'interface_meta'
____________________________________________________________________ ERROR collecting tests/materializers/types/test_scoped_term.py _____________________________________________________________________
ImportError while importing test module '/usr/ports/math/py-formulaic/work-py39/formulaic-0.5.2/tests/materializers/types/test_scoped_term.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/materializers/types/test_scoped_term.py:3: in <module>
    from formulaic.materializers.types import ScopedFactor, ScopedTerm
formulaic/__init__.py:2: in <module>
    from .materializers import FactorValues
formulaic/materializers/__init__.py:1: in <module>
    from .arrow import ArrowMaterializer
formulaic/materializers/arrow.py:1: in <module>
    from interface_meta import override
E   ModuleNotFoundError: No module named 'interface_meta'
________________________________________________________________________ ERROR collecting tests/transforms/test_basis_spline.py _________________________________________________________________________
ImportError while importing test module '/usr/ports/math/py-formulaic/work-py39/formulaic-0.5.2/tests/transforms/test_basis_spline.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/transforms/test_basis_spline.py:6: in <module>
    from formulaic.transforms.basis_spline import basis_spline
formulaic/__init__.py:2: in <module>
    from .materializers import FactorValues
formulaic/materializers/__init__.py:1: in <module>
    from .arrow import ArrowMaterializer
formulaic/materializers/arrow.py:1: in <module>
    from interface_meta import override
E   ModuleNotFoundError: No module named 'interface_meta'
__________________________________________________________________________ ERROR collecting tests/transforms/test_contrasts.py __________________________________________________________________________
ImportError while importing test module '/usr/ports/math/py-formulaic/work-py39/formulaic-0.5.2/tests/transforms/test_contrasts.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/transforms/test_contrasts.py:8: in <module>
    from formulaic.materializers import FactorValues
formulaic/__init__.py:2: in <module>
    from .materializers import FactorValues
formulaic/materializers/__init__.py:1: in <module>
    from .arrow import ArrowMaterializer
formulaic/materializers/arrow.py:1: in <module>
    from interface_meta import override
E   ModuleNotFoundError: No module named 'interface_meta'
__________________________________________________________________________ ERROR collecting tests/transforms/test_identity.py ___________________________________________________________________________
ImportError while importing test module '/usr/ports/math/py-formulaic/work-py39/formulaic-0.5.2/tests/transforms/test_identity.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/transforms/test_identity.py:1: in <module>
    from formulaic.transforms import identity
formulaic/__init__.py:2: in <module>
    from .materializers import FactorValues
formulaic/materializers/__init__.py:1: in <module>
    from .arrow import ArrowMaterializer
formulaic/materializers/arrow.py:1: in <module>
    from interface_meta import override
E   ModuleNotFoundError: No module named 'interface_meta'
____________________________________________________________________________ ERROR collecting tests/transforms/test_poly.py _____________________________________________________________________________
ImportError while importing test module '/usr/ports/math/py-formulaic/work-py39/formulaic-0.5.2/tests/transforms/test_poly.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/transforms/test_poly.py:4: in <module>
    from formulaic.transforms.poly import poly
formulaic/__init__.py:2: in <module>
    from .materializers import FactorValues
formulaic/materializers/__init__.py:1: in <module>
    from .arrow import ArrowMaterializer
formulaic/materializers/arrow.py:1: in <module>
    from interface_meta import override
E   ModuleNotFoundError: No module named 'interface_meta'
____________________________________________________________________________ ERROR collecting tests/transforms/test_scale.py ____________________________________________________________________________
ImportError while importing test module '/usr/ports/math/py-formulaic/work-py39/formulaic-0.5.2/tests/transforms/test_scale.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/transforms/test_scale.py:6: in <module>
    from formulaic.transforms import center, scale
formulaic/__init__.py:2: in <module>
    from .materializers import FactorValues
formulaic/materializers/__init__.py:1: in <module>
    from .arrow import ArrowMaterializer
formulaic/materializers/arrow.py:1: in <module>
    from interface_meta import override
E   ModuleNotFoundError: No module named 'interface_meta'
_______________________________________________________________________________ ERROR collecting tests/utils/test_cast.py _______________________________________________________________________________
ImportError while importing test module '/usr/ports/math/py-formulaic/work-py39/formulaic-0.5.2/tests/utils/test_cast.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/utils/test_cast.py:6: in <module>
    from formulaic import FactorValues
formulaic/__init__.py:2: in <module>
    from .materializers import FactorValues
formulaic/materializers/__init__.py:1: in <module>
    from .arrow import ArrowMaterializer
formulaic/materializers/arrow.py:1: in <module>
    from interface_meta import override
E   ModuleNotFoundError: No module named 'interface_meta'
=========================================================================================== warnings summary ============================================================================================
../../../../../local/lib/python3.9/site-packages/pytest_freezegun.py:17: 400 warnings
  /usr/local/lib/python3.9/site-packages/pytest_freezegun.py:17: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    if LooseVersion(pytest.__version__) < LooseVersion('3.6.0'):

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 17 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=================================================================================== 400 warnings, 17 errors in 2.63s ====================================================================================
*** Error code 2

```

**Comment by matthewwardrop** [comment] 2023-01-25 00:57
Hi @yurivict!

How did you run these tests? Interface-meta is installed as a dependency, but won't be installed if you just run `pytest`.

I cannot reproduce this.

**Comment by matthewwardrop** [comment] 2023-03-26 05:16
In the absence of followups I'll close this for now. Feel free to reopen if you are still experiencing this and need some help!

**Closed by matthewwardrop** 2023-03-26 05:16 UTC
Labels: bug, question, cannot reproduce
