### ISSUE TITLE
drop both columns in dependent variable and design matrix when missings occur

### ISSUE THREAD

**Issue by s3alfisc** [matthewwardrop/formulaic#124] opened 2022-11-26 09:45 UTC
Hi Matthew - thanks for making this super useful package available! 

Currently, when there is a missing value in a column of the design matrix X, but not in the dependent variable Y, `model_matrix()` drops observations columnwise, but not for both X and Y. 

Here's a quick example: 

```
from formulaic import model_matrix 
import numpy as np
import pandas as pd

N = 10
X = np.random.normal(0, 1, N)
Y = np.random.normal(0, 1, N)
data = {'Y':Y, 'X':X}
data = pd.DataFrame(data)

data.X.iloc[0] = None

fml = 'Y ~ X'
y, X = model_matrix(fml, data, na_action = 'ignore')
>>> y.head()
          Y
0 -0.174508
1  0.373280
2  1.631371
3 -0.622598
4 -0.482028
>>> X.head()
   Intercept         X
1        1.0  2.652463
2        1.0 -1.356067
3        1.0  1.143417
4        1.0 -1.020435
5        1.0  0.072263

y, X = model_matrix(fml, data)
>>> y.shape
(10, 1)
>>> X.shape
(9, 2)
```
The NaN column is dropped from X, but not from Y. 

I think it would be nice to add functionality for this (though it might already exist?). 

E.g. in R, before calling `base::model.matrix()`, one would define a `base::model.frame()`, which would then by default drop the entire column where a missing value exists (for both X and Y). 

```
N <- 10
X <- rnorm(N)
Y <- rnorm(N)
X[1] <- NA

data <- data.frame(Y = Y, X = X)
mf <- model.frame(Y ~ X, data)
# Y           X
# 2   0.9418535  0.05795054
# 3  -1.2333905 -1.02186716
# 4  -0.1277604  1.59699265
# 5  -0.1258892 -1.16908339
# 6   0.2176256  0.22375018
# 7  -1.2068559  0.92400472
# 8  -0.5803319  0.55442642
# 9  -1.3511992 -0.34372283
# 10 -2.0518279 -0.31997878
mm <- model.matrix(mf)

depvar <- model.response(mf)

```

**Comment by s3alfisc** [comment] 2022-11-26 10:03
Another nice feature of the R `model.frame` class is that it returns a set of informative attributes - for example, it returns an index of dropped columns. Is there a similar feature for `formulaic`? I quickly glanced over all attributes of `formulaic.model_matrix.ModelMatrix` but did not find an equivalent attribute. 

```
attributes(mf)
$names
[1] "Y" "X"

$terms
Y ~ X
attr(,"variables")
list(Y, X)
attr(,"factors")
  X
Y 0
X 1
attr(,"term.labels")
[1] "X"
attr(,"order")
[1] 1
attr(,"intercept")
[1] 1
attr(,"response")
[1] 1
attr(,".Environment")
<environment: R_GlobalEnv>
attr(,"predvars")
list(Y, X)
attr(,"dataClasses")
        Y         X 
"numeric" "numeric" 

$row.names
[1]  2  3  4  5  6  7  8  9 10

$class
[1] "data.frame"

$na.action
1 
1 
attr(,"class")
[1] "omit"

```

**Comment by matthewwardrop** [comment] 2022-11-27 23:40
Hi @s3alfisc! Thanks for reaching out!

re: nan dropping being inconsistent between the left- and right- hand sides, that's interesting. I cannot reproduce that behaviour. Which version of formulaic are you using?

re: metadata for which rows are being dropped, you're correct; formulaic doesn't propagate that information through to the `ModelSpec` (since it was not "specification", but rather data-specific state). When using pandas, however, the `index` is maintained, allowing you to determine which rows were omitted. Do you have use-cases where this would be useful?

**Comment by s3alfisc** [comment] 2022-11-28 20:16
For some reason, I was running version 0.2.4. Rookie mistake (both in not reporting the package version, and for not checking). Sorry for that! 

Here is a potentially highly specialised use case where information on dropped columns might turn out to be useful:

Assume that I want to run cluster robust inference as a post estimation command after a regression model, specified via `Y ~ X`, where some columns have been dropped due to missing values. The clustering variable is not included in the regression model, and therefore not included in the design matrix X. In order to make the post-estimation inference to work, I need to drop the dropped columns from the clustering variable too, and for that, an index of dropped columns might be useful. 

On the other hand, there is an obvious workaround

**Comment by s3alfisc** [comment] 2022-11-28 20:36
Hi Matthew, I am running version 0.5.2. Sorry for not reporting the package version, a rookie mistake. Sorry for that! Is there any other information I could provide to help debug this? 

A (potentially highly specialized) use case where metadata on dropped columns might be useful:

I want to run [cluster robust inference ](https://www.sciencedirect.com/science/article/pii/S0304407622000781) as a post estimation command after a regression model, specified via `Y ~ X`, where some columns have been dropped due to missing values. The regression model only stores the 'cleaned' X and Y as used when fitting the model. The clustering variable is not included in the regression model, and therefore not included in the design matrix X. In order to make the post-estimation inference to work, I need to drop the columns which were dropped from X and Y from the clustering variable as well, and for that, an index of dropped columns might be handy. =) 

A similar problem arises for regression models with high-dimensional fixed effects, where the fixed effects are projected out prior to running OLS on the residualized X and Y (e.g. as in the [fixest ](https://github.com/lrberge/fixest) R package). In this case, I want to keep the categorical fixed effect variable in a single column, hence create the one-hot encoded X only for variables which are not "projected out". In a second step, I then delete missing columns from both X and the fixed effect variable(s), residualize, and run OLS. 

There is an obvious workaround for both problems (even if the input is not a pandas.DataFrame): just set the `na_action  = 'ignore'` and get an index of all missing values in both X and Y myself. [Here](https://github.com/s3alfisc/pyfixest/blob/ca454c0e0fd03f45cfbc36ce5a744acf37a7f934/pyfixest/fixest.py#L184)'s a (admittedly rather convoluted) example. 

Thanks for your response, and please let me know if I can help debug this further! Best, Alex

**Comment by matthewwardrop** [comment] 2023-07-03 22:19
Hi again @s3alfisc ! I'm going to assume that the above does solve your use-cases, and close this one out. Feel free to reopen if you'd like to resume the conversation!

**Closed by matthewwardrop** 2023-07-03 22:19 UTC
Labels: question
